---
- name: Converge
  hosts: all
  become: true
  gather_facts: false

  roles:
    - role: robertdebock.mount_options
      # CI runs in a container, where no mounts are available to change, disable this test.
      # mount_options:
      #   - path: /
      #     add_options:
      #       - noexec
      #     remove_options:
      #       - noatime
